apiVersion: v1
kind: Service
metadata:
  name: alliedipfirm-web
spec:
  selector:
    app: alliedipfirm-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30004
  type: NodePort